name: GADS UI CI

on:
  push:
    tags:
      - '*'

jobs:
  build_and_release:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build UI static files
        env:
          CI: false
        run: |
          cd gads-ui && npm ci && npm run build --verbose

      - name: Build binaries
        run: |
          go get
          GOOS=windows GOARCH=amd64 go build -o GADS-x86_64.exe .
          GOOS=darwin GOARCH=amd64 go build -o GADS-darwin-amd .
          GOOS=darwin GOARCH=arm64 go build -o GADS-darwin-arm .
          GOOS=linux GOARCH=amd64 go build -o GADS-linux .
          zip -j gads-win.zip GADS-x86_64.exe
          zip -j gads-mac-amd64.zip GADS-darwin-amd
          zip -j gads-mac-arm64.zip GADS-darwin-arm
          zip -j gads-linux.zip GADS-linux

      - uses: AButler/upload-release-assets@v2.0
        with:
          files: '*.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{  github.ref_name }}